### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by yozlet** [18F/vote-gov#121]
To put the new vote.gov live, we must:

 - [x] Update the `config.votegov.urls.production` value in `package.json` to be `https://vote.gov/`
 - [x] Ensure that the `master` branch is up to date with `staging`
 - [x] Ensure that the latest `master` commit has been deployed to https://vote-gov.apps.cloud.gov/
 - [x] ~~Ensure that the `vote-gov` app in the `vote-production` space has `vote.gov` and `vote.usa.gov` added as URLs~~ _(not needed, due to CloudFront)_
 - [x] Switch origin of vote.gov CloudFront distribution to use the `vote-gov.apps.cloud.gov`
    - In **Behaviours** switch **Path Pattern** to `Default (*)` 
 - [x] Switch the S3 bucket `cloud-gov-vote-usa-gov` to redirect all requests to `https://vote.gov/`
 - [x] Check that:
    - [x] https://vote.gov/ goes to the new site
    - [x] https://www.vote.gov/ goes to the new site
    - [x] https://vote.usa.gov/ goes to the new site
    - [x] There are no errors in the JS console
    - [x] http redirects to https

**Comment by jamesharnett** [comment]
@yozlet Is there an expectation that the new vote.gov will be launched on National Voter Registration Day (Tuesday, September 27th)? I only inquire because initial launch of https://vote.gov was on the same day last year.

**Comment by yozlet** [comment]
@jamesharnett The aim is to launch it the day before (Monday). We've been working with USA.gov folks directly and I believe they've approved the launch.

**Comment by yozlet** [comment]
At 2pm Pacific we did everything up to and including the CloudFront change. However, three hours later, plenty of people are still being redirected from https://vote.gov/ to https://vote.usa.gov/ . This is because the previous redirect from vote.gov to vote.usa.gov was done with an S3 redirect, which sends 301 Permanent Redirect responses, which are cached indefinitely. (i.e. they stick around until they're either pushed out of the cache or the cache is cleared manually)

It's possible that performing the next step - having the vote.usa.gov S3 bucket redirect back to vote.gov - might force browsers to re-fetch vote.gov and see that the original redirect is gone. Alternatively, it might send browsers into a redirect loop, utterly breaking the site. (And on searching, it seems that [Firefox still does the wrong thing](https://bugzilla.mozilla.org/show_bug.cgi?id=696646).

So, for the moment, we wait.

**Comment by yozlet** [comment]
Belated update, with the story of how we fixed this:

Diego and I decided to make `vote.usa.gov` redirect back to `vote.gov`. In order to avoid all the problems we've discussed above, we did it this way:

 1. **In order to avoid ever using HTTP 301 redirects again,** we made a new redirector app in cloud.gov with the sole purpose of 302-redirecting all `vote.usa.gov` traffic to `vote.gov`. The redirector app entirely consists of a static buildpack manifest with a custom `nginx.conf` that does the redirection. It's in the repo, in [the `/redirector`folder](https://github.com/18F/vote-gov/tree/staging/redirector).
 2. **In order to avoid a redirect loop,** the redirects go to `https://vote.gov/?1` . This gets past browsers with the cached `vote.gov -> vote.usa.gov` 301.
 3. The `vote.usa.gov` CloudFront distro was repointed away from the `cloud-gov-vote-usa-gov` S3 bucket

After launch, we discovered a problem: Even a couple of hours after the changes above were deployed, some users were still seeing the old front page when visiting `vote.usa.gov`, but whatever had cached the HTML had _not_ also cached the other resources (CSS, JS, images). This meant that those users were seeing a raw, undecorated HTML page. Looking at the logs for our redirector app, I saw requests coming in for those resources, but being redirected to the front page of `vote.gov`. So I added [a line in the redirector config](https://github.com/18F/vote-gov/blob/staging/redirector/nginx.conf#L39) that redirects requests for specific `vote.usa.gov` files to the correct file in the old S3 bucket.

And with that, we consider ourselves LAUNCHED.
